import 'package:my_example_file/home/posts/models/category_model.dart';

class Categories {
  final List<CategoryModel> categories = [
    CategoryModel(id: '1', name: 'Транспорт', subcategories: [
      SubCategoryModel(id: '1.1', name: 'Автомобили'),
      SubCategoryModel(id: '1.2', name: 'Мототранспорт'),
      SubCategoryModel(id: '1.3', name: 'Грузовой и с/х транспорт'),
      SubCategoryModel(id: '1.4', name: 'Фургоны'),
      SubCategoryModel(id: '1.5', name: 'Водный транспорт'),
      SubCategoryModel(id: '1.6', name: 'Другой транспорт'),
    ]),
    CategoryModel(id: '2', name: 'Недвижимость', subcategories: [
      SubCategoryModel(id: '2.1', name: 'Квартиры'),
      SubCategoryModel(id: '2.2', name: 'Дома, коттеджи'),
      SubCategoryModel(id: '2.3', name: 'Земельные участки, дачи'),
      SubCategoryModel(id: '2.4', name: 'Коммерческая недвижимость'),
      SubCategoryModel(id: '2.5', name: 'Комнаты'),
      SubCategoryModel(id: '2.6', name: 'Гаражи и паркинги'),
      SubCategoryModel(id: '2.7', name: 'Здания, помещения'),
      SubCategoryModel(id: '2.8', name: 'Прочая недвижимость'),
    ]),
    CategoryModel(id: '3', name: 'Услуги', subcategories: [
      SubCategoryModel(id: '3.1', name: 'Фото и видеосъемка'),
      SubCategoryModel(id: '3.2', name: 'Охрана и безопасность'),
      SubCategoryModel(id: '3.3', name: 'Мебельные услуги'),
      SubCategoryModel(id: '3.4', name: 'Интернет и компьютеры'),
      SubCategoryModel(id: '3.5', name: 'Ремонт и строительство'),
      SubCategoryModel(id: '3.6', name: 'Оборудование для бизнеса'),
      SubCategoryModel(id: '3.7', name: 'Перевозки и автосервис'),
      SubCategoryModel(id: '3.8', name: 'Ремонт и обслуживание техники'),
      SubCategoryModel(id: '3.9', name: 'Прокат товаров'),
      SubCategoryModel(id: '3.10', name: 'Образование, курсы'),
      SubCategoryModel(id: '3.11', name: 'Реклама, печать'),
      SubCategoryModel(id: '3.12', name: 'Праздники и мероприятия'),
      SubCategoryModel(id: '3.13', name: 'Клининговые услуги'),
      SubCategoryModel(id: '3.14', name: 'Пошив и ремонт одежды'),
      SubCategoryModel(id: '3.15', name: 'Детские сады, няни'),
      SubCategoryModel(id: '3.16', name: 'Туристические услуги'),
      SubCategoryModel(id: '3.17', name: 'Другие услуги'),
    ]),
    CategoryModel(id: '4', name: 'Электроника', subcategories: [
      SubCategoryModel(id: '4.1', name: 'Смартфоны'),
      SubCategoryModel(id: '4.2', name: 'Гаджеты'),
      SubCategoryModel(id: '4.3', name: 'Аксессуары для телефонов'),
      SubCategoryModel(id: '4.4', name: 'Мобильные телефоны'),
      SubCategoryModel(id: '4.5', name: 'Радиотелефоны'),
      SubCategoryModel(id: '4.6', name: 'Спутниковые телефоны и коммуникаторы'),
      SubCategoryModel(id: '4.7', name: 'Аксессуары для электроники'),
      SubCategoryModel(id: '4.8', name: 'Наушники и гарнитуры'),
      SubCategoryModel(id: '4.9', name: 'Телевизоры'),
      SubCategoryModel(id: '4.10', name: 'Аудиотехника'),
      SubCategoryModel(id: '4.11', name: 'Фото- и видеокамеры'),
      SubCategoryModel(id: '4.12', name: 'Развлечения'),
      SubCategoryModel(id: '4.13', name: 'Видеотехника'),
      SubCategoryModel(id: '4.14', name: 'Сценическое оборудование'),
      SubCategoryModel(id: '4.15', name: 'Ноутбуки и аксессуары'),
      SubCategoryModel(id: '4.16', name: 'Настольные компьютеры'),
      SubCategoryModel(id: '4.17', name: 'Планшеты и аксессуары'),
      SubCategoryModel(id: '4.18', name: 'Периферия'),
      SubCategoryModel(id: '4.19', name: 'Комплектующие для компьютера'),
      SubCategoryModel(id: '4.20', name: 'Сетевое оборудование'),
      SubCategoryModel(id: '4.21', name: 'Оргтехника и расходные материалы'),
      SubCategoryModel(
          id: '4.22', name: 'Электронное оборудование для торговли'),
      SubCategoryModel(
          id: '4.23', name: 'IP-телефония и конференц-оборудование'),
      SubCategoryModel(id: '4.24', name: 'Программное обеспечение'),
    ]),
    CategoryModel(id: '5', name: 'Бытовая техника', subcategories: [
      SubCategoryModel(id: '5.1', name: 'Техника для кухни'),
      SubCategoryModel(id: '5.2', name: 'Техника для дома'),
      SubCategoryModel(id: '5.3', name: 'Климатическая техника'),
      SubCategoryModel(id: '5.4', name: 'Крупная бытовая техника'),
      SubCategoryModel(id: '5.5', name: 'Торговые автоматы'),
      SubCategoryModel(id: '5.6', name: 'Техника и оборудование для красоты'),
    ]),
    CategoryModel(id: '6', name: 'Работа', subcategories: [
      SubCategoryModel(id: '6.1', name: 'Административный персонал'),
      SubCategoryModel(id: '6.2', name: 'Торговля, продажи'),
      SubCategoryModel(id: '6.3', name: 'Такси, логистика, доставка'),
      SubCategoryModel(id: '6.4', name: 'Недвижимость'),
      SubCategoryModel(id: '6.5', name: 'Образование, наука'),
      SubCategoryModel(id: '6.6', name: 'Маркетинг, реклама, PR'),
      SubCategoryModel(id: '6.7', name: 'IT, компьютеры, связь'),
      SubCategoryModel(id: '6.8', name: 'Швейное дело'),
      SubCategoryModel(id: '6.9', name: 'Склад'),
      SubCategoryModel(id: '6.10', name: 'Охрана и безопасность'),
      SubCategoryModel(id: '6.11', name: 'Строительные специальности'),
      SubCategoryModel(id: '6.12', name: 'Салоны красоты'),
      SubCategoryModel(id: '6.13', name: 'Домашний персонал и уборка'),
      SubCategoryModel(id: '6.14', name: 'Добыча сырья'),
      SubCategoryModel(id: '6.15', name: 'Туризм, гостиницы, рестораны'),
      SubCategoryModel(id: '6.16', name: 'Автобизнес, сервисное обслуживание'),
      SubCategoryModel(id: '6.17', name: 'Медицина, фармацевтика'),
      SubCategoryModel(id: '6.18', name: 'Развлечения, спорт'),
      SubCategoryModel(id: '6.19', name: 'Работа за рубежом'),
      SubCategoryModel(id: '6.20', name: 'Начало карьеры, студенты'),
      SubCategoryModel(id: '6.21', name: 'Волонтерство и благотворительность'),
      SubCategoryModel(id: '6.22', name: 'Другие сферы деятельности'),
    ]),
    CategoryModel(id: '7', name: 'Бытовая химия, хозтовары', subcategories: [
      SubCategoryModel(id: '7.1', name: 'Средства для стирки'),
      SubCategoryModel(id: '7.2', name: 'Туалетное и жидкое мыло'),
      SubCategoryModel(id: '7.3', name: 'Моющие средства для посуды'),
      SubCategoryModel(id: '7.4', name: 'Универсальные чистящие средства'),
      SubCategoryModel(
          id: '7.5', name: 'Чистящие средства для сантехники, кафеля и труб'),
      SubCategoryModel(id: '7.6', name: 'Средства для мытья пола и стен'),
      SubCategoryModel(
          id: '7.7', name: 'Средства для чистки кухонных поверхностей'),
      SubCategoryModel(id: '7.8', name: 'Средства для посудомоечных машин'),
      SubCategoryModel(id: '7.9', name: 'Освежители воздуха'),
      SubCategoryModel(id: '7.10', name: 'Средства против насекомых'),
      SubCategoryModel(id: '7.11', name: 'Средства для мытья стекол'),
      SubCategoryModel(
          id: '7.12', name: 'Средства для ухода за бытовой техникой'),
      SubCategoryModel(
          id: '7.13', name: 'Средства для мебели, ковров и напольных покрытий'),
      SubCategoryModel(id: '7.14', name: 'Средства для глажки и антистатики'),
      SubCategoryModel(id: '7.15', name: 'Наборы бытовой химии'),
      SubCategoryModel(id: '7.16', name: 'Нейтрализаторы запахов'),
      SubCategoryModel(id: '7.17', name: 'Бумажная продукция для дома'),
      SubCategoryModel(id: '7.18', name: 'Инвентарь для уборки'),
      SubCategoryModel(id: '7.19', name: 'Аксессуары для ванны и туалета'),
      SubCategoryModel(
          id: '7.20', name: 'Коробки, ящики и корзины для хранения'),
      SubCategoryModel(id: '7.21', name: 'Аксессуары для кухни'),
      SubCategoryModel(id: '7.22', name: 'Уход за одеждой и обувью'),
      SubCategoryModel(id: '7.23', name: 'Упаковочные материалы'),
    ]),
    CategoryModel(id: '8', name: 'Аптека, здоровье', subcategories: [
      SubCategoryModel(id: '8.1', name: 'Витамины и БАД'),
      SubCategoryModel(id: '8.2', name: 'Оптика'),
      SubCategoryModel(id: '8.3', name: 'Ортопедия'),
      SubCategoryModel(
          id: '8.4', name: 'Антисептики и дезинфицирующие средства'),
      SubCategoryModel(id: '8.5', name: 'Медицинские приборы'),
      SubCategoryModel(id: '8.6', name: 'Бандажи, корсеты, корректоры'),
      SubCategoryModel(id: '8.7', name: 'Инвалидные коляски'),
      SubCategoryModel(id: '8.8', name: 'Другие медицинские товары'),
    ]),
    CategoryModel(id: '9', name: 'Красота', subcategories: [
      SubCategoryModel(id: '9.1', name: 'Уход за лицом'),
      SubCategoryModel(id: '9.2', name: 'Уход за волосами'),
      SubCategoryModel(id: '9.3', name: 'Уход за телом'),
      SubCategoryModel(id: '9.4', name: 'Гигиена полости рта'),
      SubCategoryModel(id: '9.5', name: 'Средства личной гигиены'),
      SubCategoryModel(id: '9.6', name: 'Декоративная косметика'),
      SubCategoryModel(id: '9.7', name: 'Парфюмерия'),
      SubCategoryModel(id: '9.8', name: 'Ароматерапия'),
      SubCategoryModel(id: '9.9', name: 'Массажёры'),
      SubCategoryModel(id: '9.10', name: 'Для маникюра и педикюра'),
      SubCategoryModel(id: '9.11', name: 'Наборы косметики'),
      SubCategoryModel(id: '9.12', name: 'Товары для бритья'),
      SubCategoryModel(id: '9.13', name: 'Аксессуары для красоты'),
    ]),
    CategoryModel(id: '10', name: 'Продукты питания', subcategories: [
      SubCategoryModel(id: '10.1', name: 'Готовая еда, кулинария'),
      SubCategoryModel(id: '10.2', name: 'Молочные продукты и яйца'),
      SubCategoryModel(id: '10.3', name: 'Овощи, фрукты'),
      SubCategoryModel(id: '10.4', name: 'Колбасы и сосиски'),
      SubCategoryModel(id: '10.5', name: 'Птица'),
      SubCategoryModel(id: '10.6', name: 'Рыба и морепродукты'),
      SubCategoryModel(id: '10.7', name: 'Хлеб, выпечка'),
      SubCategoryModel(id: '10.8', name: 'Макароны и крупы'),
      SubCategoryModel(id: '10.9', name: 'Сладости'),
      SubCategoryModel(id: '10.10', name: 'Всё для готовки'),
      SubCategoryModel(id: '10.11', name: 'Всё для выпечки'),
      SubCategoryModel(id: '10.12', name: 'Консервы и соленья'),
      SubCategoryModel(id: '10.13', name: 'Чипсы, орехи и снэки'),
      SubCategoryModel(id: '10.14', name: 'Чай и кофе'),
      SubCategoryModel(id: '10.15', name: 'Замороженные продукты'),
      SubCategoryModel(id: '10.16', name: 'Сок, вода и напитки'),
    ]),
    CategoryModel(id: '11', name: 'Автотовары', subcategories: [
      SubCategoryModel(id: '11.1', name: 'Шины'),
      SubCategoryModel(id: '11.2', name: 'Автозапчасти'),
      SubCategoryModel(id: '11.3', name: 'Автохимия и автокосметика'),
      SubCategoryModel(id: '11.4', name: 'Автоаксессуары'),
      SubCategoryModel(id: '11.5', name: 'Автомобильное оборудование'),
      SubCategoryModel(id: '11.6', name: 'Масла и технические жидкости'),
      SubCategoryModel(id: '11.7', name: 'Комплекты дисков'),
      SubCategoryModel(id: '11.8', name: 'Аккумуляторы'),
      SubCategoryModel(id: '11.9', name: 'Автоэлектроника'),
      SubCategoryModel(id: '11.10', name: 'Автомобильное освещение'),
      SubCategoryModel(id: '11.11', name: 'Автоакустика'),
      SubCategoryModel(id: '11.12', name: 'Защита и внешний тюнинг'),
      SubCategoryModel(id: '11.13', name: 'Автоинструменты'),
      SubCategoryModel(
          id: '11.14', name: 'Автомобильные противоугонные устройства'),
      SubCategoryModel(id: '11.15', name: 'Автосервисное оборудование'),
      SubCategoryModel(id: '11.16', name: 'Спецтехника и мототехника'),
      SubCategoryModel(id: '11.17', name: 'Мотоэкипировка'),
      SubCategoryModel(id: '11.18', name: 'Багажные системы'),
      SubCategoryModel(id: '11.19', name: 'ГБО'),
    ]),
    CategoryModel(id: '12', name: 'Животные', subcategories: [
      SubCategoryModel(id: '12.1', name: 'Кошки'),
      SubCategoryModel(id: '12.2', name: 'Собаки'),
      SubCategoryModel(id: '12.3', name: 'С/х животные'),
      SubCategoryModel(id: '12.4', name: 'Птицы'),
      SubCategoryModel(id: '12.5', name: 'Аквариумы, аквариумные рыбки'),
      SubCategoryModel(id: '12.6', name: 'Грызуны'),
      SubCategoryModel(id: '12.7', name: 'Экзотические животные'),
      SubCategoryModel(id: '12.8', name: 'Услуги для животных'),
      SubCategoryModel(id: '12.9', name: 'Другие животные'),
    ]),
    CategoryModel(id: '13', name: 'Товары для животных', subcategories: [
      SubCategoryModel(id: '13.1', name: 'Для кошек'),
      SubCategoryModel(id: '13.2', name: 'Для собак'),
      SubCategoryModel(id: '13.3', name: 'Гигиена и уход за животными'),
      SubCategoryModel(id: '13.4', name: 'Аксессуары для животных'),
      SubCategoryModel(id: '13.5', name: 'Ветаптека'),
      SubCategoryModel(id: '13.6', name: 'Для рыб и рептилий'),
      SubCategoryModel(id: '13.7', name: 'Для птиц'),
      SubCategoryModel(id: '13.8', name: 'Для грызунов'),
      SubCategoryModel(id: '13.9', name: 'Груминг'),
      SubCategoryModel(id: '13.10', name: 'Для сельскохозяйственных животных'),
    ]),
    CategoryModel(id: '14', name: 'Товары для дома и сада', subcategories: [
      SubCategoryModel(id: '14.1', name: 'Посуда и принадлежности'),
      SubCategoryModel(id: '14.2', name: 'Домашний текстиль'),
      SubCategoryModel(id: '14.3', name: 'Дача, сад и огород'),
      SubCategoryModel(id: '14.4', name: 'Интерьер'),
      SubCategoryModel(id: '14.5', name: 'Умный дом'),
      SubCategoryModel(id: '14.6', name: 'Освещение'),
      SubCategoryModel(id: '14.7', name: 'Товары для праздников'),
      SubCategoryModel(id: '14.8', name: 'Мебель'),
    ]),
    CategoryModel(id: '15', name: 'Строительство, ремонт', subcategories: [
      SubCategoryModel(id: '15.1', name: 'Инструменты'),
      SubCategoryModel(id: '15.2', name: 'Двери, окна, лестницы'),
      SubCategoryModel(id: '15.3', name: 'Сантехника'),
      SubCategoryModel(id: '15.4', name: 'Электрика'),
      SubCategoryModel(id: '15.5', name: 'Водоснабжение'),
      SubCategoryModel(id: '15.6', name: 'Системы отопления и вентиляции'),
      SubCategoryModel(id: '15.7', name: 'Системы безопасности'),
      SubCategoryModel(id: '15.8', name: 'Отделочные материалы'),
      SubCategoryModel(id: '15.9', name: 'Строительные материалы'),
      SubCategoryModel(id: '15.10', name: 'Строительное оборудование'),
      SubCategoryModel(id: '15.11', name: 'Лакокрасочные материалы'),
      SubCategoryModel(id: '15.12', name: 'Строительный крепеж'),
      SubCategoryModel(id: '15.13', name: 'Баня и сауна'),
      SubCategoryModel(id: '15.14', name: 'Кровля, фасад, ворота и ограждения'),
    ]),
    CategoryModel(id: '16', name: 'Детский мир', subcategories: [
      SubCategoryModel(id: '16.1', name: 'Детская одежда'),
      SubCategoryModel(id: '16.2', name: 'Детская обувь'),
      SubCategoryModel(id: '16.3', name: 'Детский транспорт'),
      SubCategoryModel(id: '16.4', name: 'Игрушки'),
      SubCategoryModel(id: '16.5', name: 'Детская мебель'),
      SubCategoryModel(id: '16.6', name: 'Детское питание'),
      SubCategoryModel(id: '16.7', name: 'Для малыша и мамы'),
    ]),
    CategoryModel(id: '17', name: 'Канцелярские товары', subcategories: [
      SubCategoryModel(id: '17.1', name: 'Бумага и бумажная продукция'),
      SubCategoryModel(id: '17.2', name: 'Письменные принадлежности'),
      SubCategoryModel(id: '17.3', name: 'Офисные принадлежности'),
      SubCategoryModel(id: '17.4', name: 'Школьные принадлежности'),
      SubCategoryModel(id: '17.5', name: 'Демонстрационные доски'),
      SubCategoryModel(id: '17.6', name: 'Торговые и рекламные принадлежности'),
      SubCategoryModel(id: '17.7', name: 'Мелкоофисные принадлежности'),
      SubCategoryModel(id: '17.8', name: 'Постпечатное оборудование'),
      SubCategoryModel(id: '17.9', name: 'Штемпельные принадлежности'),
      SubCategoryModel(id: '17.10', name: 'Чертежные принадлежности'),
    ]),
    CategoryModel(id: '18', name: 'Досуг, книги', subcategories: [
      SubCategoryModel(id: '18.1', name: 'Хобби и творчество'),
      SubCategoryModel(id: '18.2', name: 'Книги'),
      SubCategoryModel(id: '18.3', name: 'Настольные игры'),
      SubCategoryModel(id: '18.4', name: 'Музыкальные инструменты'),
    ]),
    CategoryModel(id: '19', name: 'Спорт, туризм', subcategories: [
      SubCategoryModel(id: '19.1', name: 'Самокаты, гироскутеры, моноколеса'),
      SubCategoryModel(id: '19.2', name: 'Велоспорт'),
      SubCategoryModel(id: '19.3', name: 'Спорт и отдых'),
      SubCategoryModel(id: '19.4', name: 'Товары для фитнеса'),
      SubCategoryModel(id: '19.5', name: 'Искусство и коллекционирование'),
      SubCategoryModel(id: '19.6', name: 'Спортивное питание'),
      SubCategoryModel(id: '19.7', name: 'Для самообороны'),
      SubCategoryModel(id: '19.8', name: 'Туризм и отдых на природе'),
    ]),
    CategoryModel(id: '20', name: 'Туризм', subcategories: [
      SubCategoryModel(id: '20.1', name: 'Туры и путевки'),
      SubCategoryModel(id: '20.2', name: 'Отдых на Иссык-Куле'),
    ]),
    CategoryModel(id: '21', name: 'Одежда', subcategories: [
      SubCategoryModel(id: '21.1', name: 'Женская одежда'),
      SubCategoryModel(id: '21.2', name: 'Мужская одежда'),
      SubCategoryModel(id: '21.3', name: 'Женская обувь'),
      SubCategoryModel(id: '21.4', name: 'Мужская обувь'),
      SubCategoryModel(id: '21.5', name: 'Спецодежда'),
    ]),
    CategoryModel(id: '22', name: 'Аксессуары', subcategories: [
      SubCategoryModel(id: '22.1', name: 'Сумки, чемоданы, кошельки'),
      SubCategoryModel(id: '22.2', name: 'Шапки, шарфы, перчатки'),
      SubCategoryModel(id: '22.3', name: 'Аксессуары для волос'),
      SubCategoryModel(id: '22.4', name: 'Зонты, брелоки и портсигары'),
      SubCategoryModel(id: '22.5', name: 'Часы'),
      SubCategoryModel(id: '22.6', name: 'Очки и аксессуары'),
      SubCategoryModel(id: '22.7', name: 'Атрибуты одежды'),
      SubCategoryModel(id: '22.8', name: 'Свадебные аксессуары'),
      SubCategoryModel(id: '22.9', name: 'Ювелирные украшения'),
      SubCategoryModel(id: '22.10', name: 'Бижутерия'),
      SubCategoryModel(
          id: '22.11', name: 'Ювелирное оборудование, подставки и фурнитура'),
    ]),
    CategoryModel(id: '23', name: 'Находки, отдам даром', subcategories: [
      SubCategoryModel(id: '23.1', name: 'Отдам даром'),
      SubCategoryModel(id: '23.2', name: 'Бюро находок'),
    ]),
  ];
}
